[package]
name = "ieql"
version = "0.1.0"
authors = ["Miles McCain <0@rmrm.io>"]

[dependencies]
regex = "1.1.0"
serde = "1.0"
serde_derive = "1.0"
ron = "0.4"
url = "1.7.2"
clap = "2.32"
simplelog = "0.5"
log = "0.4"

[[bin]]
name = "ieql"
path = "src/cli/bin.rs"
doc = false